POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "description": "Testing",
    "date": "1-1-01",
    "specialist" : "Dr. House",
    "type": "OccupationalHealthcare",
    "employerName": "AYX"
}